	gpu_qsys u0 (
		.clk_clk                                 (<connected-to-clk_clk>),                                 //                               clk.clk
		.gpu_main_external_interface_address     (<connected-to-gpu_main_external_interface_address>),     //       gpu_main_external_interface.address
		.gpu_main_external_interface_byte_enable (<connected-to-gpu_main_external_interface_byte_enable>), //                                  .byte_enable
		.gpu_main_external_interface_read        (<connected-to-gpu_main_external_interface_read>),        //                                  .read
		.gpu_main_external_interface_write       (<connected-to-gpu_main_external_interface_write>),       //                                  .write
		.gpu_main_external_interface_write_data  (<connected-to-gpu_main_external_interface_write_data>),  //                                  .write_data
		.gpu_main_external_interface_acknowledge (<connected-to-gpu_main_external_interface_acknowledge>), //                                  .acknowledge
		.gpu_main_external_interface_read_data   (<connected-to-gpu_main_external_interface_read_data>),   //                                  .read_data
		.instr_fifo_out_valid                    (<connected-to-instr_fifo_out_valid>),                    //                    instr_fifo_out.valid
		.instr_fifo_out_data                     (<connected-to-instr_fifo_out_data>),                     //                                  .data
		.instr_fifo_out_ready                    (<connected-to-instr_fifo_out_ready>),                    //                                  .ready
		.memory_mem_a                            (<connected-to-memory_mem_a>),                            //                            memory.mem_a
		.memory_mem_ba                           (<connected-to-memory_mem_ba>),                           //                                  .mem_ba
		.memory_mem_ck                           (<connected-to-memory_mem_ck>),                           //                                  .mem_ck
		.memory_mem_ck_n                         (<connected-to-memory_mem_ck_n>),                         //                                  .mem_ck_n
		.memory_mem_cke                          (<connected-to-memory_mem_cke>),                          //                                  .mem_cke
		.memory_mem_cs_n                         (<connected-to-memory_mem_cs_n>),                         //                                  .mem_cs_n
		.memory_mem_ras_n                        (<connected-to-memory_mem_ras_n>),                        //                                  .mem_ras_n
		.memory_mem_cas_n                        (<connected-to-memory_mem_cas_n>),                        //                                  .mem_cas_n
		.memory_mem_we_n                         (<connected-to-memory_mem_we_n>),                         //                                  .mem_we_n
		.memory_mem_reset_n                      (<connected-to-memory_mem_reset_n>),                      //                                  .mem_reset_n
		.memory_mem_dq                           (<connected-to-memory_mem_dq>),                           //                                  .mem_dq
		.memory_mem_dqs                          (<connected-to-memory_mem_dqs>),                          //                                  .mem_dqs
		.memory_mem_dqs_n                        (<connected-to-memory_mem_dqs_n>),                        //                                  .mem_dqs_n
		.memory_mem_odt                          (<connected-to-memory_mem_odt>),                          //                                  .mem_odt
		.memory_mem_dm                           (<connected-to-memory_mem_dm>),                           //                                  .mem_dm
		.memory_oct_rzqin                        (<connected-to-memory_oct_rzqin>),                        //                                  .oct_rzqin
		.prim_assembly_fifo_in_valid             (<connected-to-prim_assembly_fifo_in_valid>),             //             prim_assembly_fifo_in.valid
		.prim_assembly_fifo_in_data              (<connected-to-prim_assembly_fifo_in_data>),              //                                  .data
		.prim_assembly_fifo_in_ready             (<connected-to-prim_assembly_fifo_in_ready>),             //                                  .ready
		.prim_assembly_fifo_out_valid            (<connected-to-prim_assembly_fifo_out_valid>),            //            prim_assembly_fifo_out.valid
		.prim_assembly_fifo_out_data             (<connected-to-prim_assembly_fifo_out_data>),             //                                  .data
		.prim_assembly_fifo_out_ready            (<connected-to-prim_assembly_fifo_out_ready>),            //                                  .ready
		.raster_fifo_in_valid                    (<connected-to-raster_fifo_in_valid>),                    //                    raster_fifo_in.valid
		.raster_fifo_in_data                     (<connected-to-raster_fifo_in_data>),                     //                                  .data
		.raster_fifo_in_ready                    (<connected-to-raster_fifo_in_ready>),                    //                                  .ready
		.raster_fifo_out_valid                   (<connected-to-raster_fifo_out_valid>),                   //                   raster_fifo_out.valid
		.raster_fifo_out_data                    (<connected-to-raster_fifo_out_data>),                    //                                  .data
		.raster_fifo_out_ready                   (<connected-to-raster_fifo_out_ready>),                   //                                  .ready
		.reset_reset                             (<connected-to-reset_reset>),                             //                             reset.reset
		.vert_processing_fifo_in_valid           (<connected-to-vert_processing_fifo_in_valid>),           //           vert_processing_fifo_in.valid
		.vert_processing_fifo_in_data            (<connected-to-vert_processing_fifo_in_data>),            //                                  .data
		.vert_processing_fifo_in_ready           (<connected-to-vert_processing_fifo_in_ready>),           //                                  .ready
		.vert_processing_fifo_out_valid          (<connected-to-vert_processing_fifo_out_valid>),          //          vert_processing_fifo_out.valid
		.vert_processing_fifo_out_data           (<connected-to-vert_processing_fifo_out_data>),           //                                  .data
		.vert_processing_fifo_out_ready          (<connected-to-vert_processing_fifo_out_ready>),          //                                  .ready
		.vga_controller_external_interface_CLK   (<connected-to-vga_controller_external_interface_CLK>),   // vga_controller_external_interface.CLK
		.vga_controller_external_interface_HS    (<connected-to-vga_controller_external_interface_HS>),    //                                  .HS
		.vga_controller_external_interface_VS    (<connected-to-vga_controller_external_interface_VS>),    //                                  .VS
		.vga_controller_external_interface_BLANK (<connected-to-vga_controller_external_interface_BLANK>), //                                  .BLANK
		.vga_controller_external_interface_SYNC  (<connected-to-vga_controller_external_interface_SYNC>),  //                                  .SYNC
		.vga_controller_external_interface_R     (<connected-to-vga_controller_external_interface_R>),     //                                  .R
		.vga_controller_external_interface_G     (<connected-to-vga_controller_external_interface_G>),     //                                  .G
		.vga_controller_external_interface_B     (<connected-to-vga_controller_external_interface_B>),     //                                  .B
		.video_pll_ref_clk_clk                   (<connected-to-video_pll_ref_clk_clk>)                    //                 video_pll_ref_clk.clk
	);

